### ISSUE TITLE
CLA is not completing as expected

### ISSUE THREAD

**Issue by GordonArber** [UnityTechnologies/open-project-1#103]
**Short description**
When I go through the process of signing the CLA, it never verifies that I have completed it.

**Expected behaviour**
I expect the CLA badge to turn green and to allow me to complete PRs.

**To Reproduce**
1. I click the "details" link: ![CLA1](https://user-images.githubusercontent.com/19920780/97024103-699f8500-1524-11eb-833a-488a3fd19e1c.jpg)
2. I click the blue "Sign  in with GitHub to agree": 
![CLA2](https://user-images.githubusercontent.com/19920780/97024244-93f14280-1524-11eb-9983-b604794c8770.jpg)
3. I let it redirect me back to the PR: 
![CLA3](https://user-images.githubusercontent.com/19920780/97024292-a4a1b880-1524-11eb-92dd-b0e4079c46e4.jpg)

**Notes**
- This is the 3rd time I am trying to complete this in the past week. I would appreciate any sort of help.

**Comment by DeivSky** [comment]
Make sure that the email you made the commit with is configured in your GitHub account.

**Comment by GordonArber** [comment]
> Make sure that the email you made the commit with is configured in your GitHub account.

Yeah, I did a bunch of research and saw this as a possible reason for this issue. I checked all of my emails match up. It's really weird.

**Comment by GordonArber** [comment]
Ok I got it resolved. There was some sort of weird old email issue with my account. It appears I have it resolved.
