### ISSUE TITLE
remove DeivSky.StateMachine 

### ISSUE THREAD

**Issue by ErikBehar** [UnityTechnologies/open-project-1#107]
**Short description**
current code doesnt compile due to DeivSky.StateMachine assembly and
existing entries in code  

**Expected behaviour**
Code compiles on clean checkout from repo 

**To Reproduce**
1. clone from repo
2. open project in unity
3. see compile errors

**Notes**
resolved by removing UOP1.StateMachine assembly
do a search and replace in code:
search for: DeivSky.StateMachine
replace with: UOP1.StateMachine

**Comment by ciro-unity** [comment]
Thanks, very good quick catch! I pushed the fix.
