### ISSUE TITLE
Baked geometry becomes black when no dynamic geometry is on screen

### ISSUE THREAD

**Issue by ciro-unity** [UnityTechnologies/open-project-1#108]
**Short description**
When using the toon shader, baked geometry becomes black when no dynamic geometry is present on screen.

**To Reproduce**
1. Pull the art-assets branch ([this commit](https://github.com/UnityTechnologies/open-project-1/commit/d2067b98aa10cee14a575c5a4e73176c4afcd1da), or more recent).
2. Open the ArtShowcase scene.
3. Make sure any object is marked as static (preferrably the ground too).
4. Bake lighting. Wait for Unity to finish.
5. Now look at the object, without having any non-baked object on screen.

**Notes**
- The issue seems to lie in how the custom toon shader treats shadows cast by dynamic objects on static geometry. When no object is in the view, the issue occurs as if the static geometry is now "all shadowed".
- The issue might be not in the shader, but in the pipeline or in the custom .hlsl code used in the shader.
- Video of the issue:

[![image](https://user-images.githubusercontent.com/20049224/97590534-01a6de00-19ff-11eb-9420-0af41805e934.png)](https://youtu.be/0HOBL3afYLM)

**Comment by ciro-unity** [comment]
I already have a clue on why it happens. Will fix it as soon as I have time.

**Comment by yopparai** [comment]
oops I created PR just right now

**Comment by ciro-unity** [comment]
> oops I created PR just right now

It's ok, if your fix works I'll merge yours! :)

**Comment by ciro-unity** [comment]
Fixed!
