### ISSUE TITLE
[Feedback] Mention the target Unity Version

### ISSUE THREAD

**Issue by TJHeuvel** [UnityTechnologies/open-project-1#11]
Only by digging through the repo did i find that Unity 2019.4.7f1 was used last, it would be preferable if the intended version was mentioned somewhere in the readme or contributing manual.

**Comment by ciro-unity** [comment]
That's a great suggestion and I honestly don't know how I managed to miss mentioning it. I'm adding it where it makes sense! Thanks Tijmen!
