### ISSUE TITLE
The state machine stops working when a state transition has many conditions

### ISSUE THREAD

**Issue by GFX5000i** [UnityTechnologies/open-project-1#111]
**Short description**
When a state transition has 4 or more conditions in a specific setup the exception _ArgumentOutOfRangeException_ is thrown and the character stops moving.

**Expected behaviour**
The state transition should allow as many conditions as needed and with any setting without throwing errors.

**To Reproduce**
1. Go to _Assets/ScriptableObjects/Protagonist/Transitions/BeginJumpDescent.asset_
2. Set the conditions as shown in the print screen attached
3. Enter Play Mode
4. The exception is thrown, the state machine stops and the character won't move

**Notes**
- The full stack trace: [Stack Trace.txt](https://github.com/UnityTechnologies/open-project-1/files/5441977/Stack.Trace.txt)
- The exception source: _Assets/Scripts/StateMachine/ScriptableObjects/StateTransitionSO.ProcessConditionUsages()_

![StateTransition Exception](https://user-images.githubusercontent.com/16827309/97237782-9c68a800-17c6-11eb-8a5f-bdb811b8f5ea.png)

**Comment by DeivSky** [comment]
Hey, good catch! Can I ask you to see if you can replicate it without repeating any conditions?
