### ISSUE TITLE
Walking state constantly switching to JumpDescent and back

### ISSUE THREAD

**Issue by GFX5000i** [UnityTechnologies/open-project-1#115]
**Short description**
The Walking state is constantly switching to JumpDescent and back to Walking when moving the character.

**Expected behaviour**
The character should maintain the Walking state while in flat ground and small slopes.

**To Reproduce**
1. Enter Play Mode
2. Select the GameObject Pig(Clone)
3. Activate in the inspector: StateMachine > Debug [X]
4. Move the character around without jumping
5. Observe the field: StateMachine > Current State
AND/OR
6. Check the console messages

**Notes**
The issue seems to have no practical impact in the game right now, but could create other issues when adding extra actions like footsteps audio and walking animation.

**Console messages**
![Walking console](https://user-images.githubusercontent.com/16827309/97361192-f7a9a180-187d-11eb-9eaa-12caf71199db.png)

**Comment by ciro-unity** [comment]
Great catch, I saw it happening during the livestream yesterday and I was like "wtf?" :D It's great you already fixed it.
