### ISSUE TITLE
Spawn System not spawning the player when loading scene from the LocationLoader

### ISSUE THREAD

**Issue by Javimtib92** [UnityTechnologies/open-project-1#120]
**Short description**
Player doesn't get instantiated by SpawnSystem when Scene is loaded by the LocationLoader

**Expected behaviour**
When scene is loaded via the LocationLoader player should be spawned in the scene

**To Reproduce**
1. Go to LoadingTest/Beach Scene
2. Add the SpawnSystem and everything necessary to spawn the protagonist
3. Go to the SceneLoading Scene
4. Click Play
5. When the menu appears click Start
6. When Beach Scene is loaded check the screen to see if player was instantiated

**Notes**
- Maybe it's too early to create this issue, but I noticed this by playing a little bit with the LocationLoader, for the record a workaround is to go to the SpawnSystem class and Spawn on the Start method instead of the Awake, but maybe that is not a solid fix.

- Please @ciro-unity close this issue if you think it's too early to add it

**Comment by ciro-unity** [comment]
It might be a tad early, but I'll keep it open as a reminder, why not!

**Comment by HemangMaan** [comment]
Sir, I would like to contribute and fix this bug.

**Comment by ciro-unity** [comment]
> Sir, I would like to contribute and fix this bug.

Sorry, there's already a PR which claims to be fixing it, I just linked it: #136
