### ISSUE TITLE
Character can climb the mountain with well timed jumps

### ISSUE THREAD

**Issue by GFX5000i** [UnityTechnologies/open-project-1#123]
**Short description**
Character can climb the mountain without sliding back down by landing the jump when the character is not moving (WASD keys are not being pressed)
The moment the character moves, it begins sliding.

**Expected behaviour**
The character should slide down when landing in steep slopes, even without moving.

**To Reproduce**
1. Jump towards the mountain and stop moving before touching the ground
2. Jump again and only move while in the air
3. Plant a flag on the top of the mountain 😆

**Notes**
- The Idle and JumpDescending states don't have a StartSliding transition.

### Reaching the mountain top
![Mountain Peak](https://user-images.githubusercontent.com/16827309/97508135-a1139480-195d-11eb-81cf-08fe041372e6.png)

### The FSM debug
![Mountain Console](https://user-images.githubusercontent.com/16827309/97508143-a7a20c00-195d-11eb-95ce-1bb574dec290.png)

**Comment by davejrodriguez** [comment]
Sounds like a feature 🙂
