### ISSUE TITLE
Player input not responsive  if the game is under heavy load..

### ISSUE THREAD

**Issue by rainaldisatria** [UnityTechnologies/open-project-1#127]
Player input become not responsive if the game is under heavy load.

**How to reproduce:**
- Directly after the game start, press the start button (going to the beach scene).
- After you are in beach scene, quickly tap any player movement input (S for ex.)
- hold it for 3s, then release. The moment you release the input, the player is still moving 

**Note:** 
- I'm using Unity 2020.1.6f1
- using latest commit

Video:
https://youtu.be/117PkDAZQJo

**Comment by rainaldisatria** [comment]
mmmmmmmmm, not reproducible after restarting Unity :joy: .
closed.

**Comment by laylayslay55** [comment]
gg
