### ISSUE TITLE
Player jump doesn't get canceled upon hitting an object

### ISSUE THREAD

**Issue by Quickz** [UnityTechnologies/open-project-1#15]
#**Short description**
When performing a jump the player stays in the air even when he hits an object from above until the jump is finished.

**Expected behaviour**
The jump should stop instantly and the player should start falling down.

**To Reproduce**
1. Go to 'CharController' scene
2. Run the project
3. Move your character so that there's an obstacle above his head
4. Jump

**Notes**
https://streamable.com/dgse30

**Comment by OldManCharles** [comment]
I'd like to fix this one!

**Comment by ciro-unity** [comment]
Great find, love that you attached a video of the issue!

**Comment by ciro-unity** [comment]
Fixed in PR #16

**Comment by 0479010347** [comment]
- Is this app use full
