### ISSUE TITLE
Unused metafile for Sound

### ISSUE THREAD

**Issue by fqureshi** [UnityTechnologies/open-project-1#165]
**Short description**
An unused meta file for Sound made it through after we merged our new Audio System.

**Expected behaviour**
There should be no extraneous meta files that reference things that don't exist.

**To Reproduce**
1. Open unity
2. Read Console warnings

**Comment by fqureshi** [comment]
Hmm, looks like I don't have permissions to link this issue to the PR.

Anyways, here's the PR for the quick fix: https://github.com/UnityTechnologies/open-project-1/pull/166

**Comment by ciro-unity** [comment]
Thanks @fqureshi. I'll merge the PR soon.
For these super minor bugs there's no need to open an issue, by the way!
