### ISSUE TITLE
Character can climb steep surfaces

### ISSUE THREAD

**Issue by antoniucraciun** [UnityTechnologies/open-project-1#167]
**Short description**
Player character can climb steep surface by repeatedly pressing space and holding down direction buttons, while facing the the surface.

**Expected behaviour**
When trying to jump on steep surfaces the character should fall back down

**To Reproduce**
1. Open 'CharController' scene
2. Click on 'Play button'
3. Move close to a steep surface, like the mountain
4. Continue pressing W and A or D and the character will climb the surface

**Notes**
In need of more information, please let me know, I will record a video of how I managed to do it.
![characterBug](https://user-images.githubusercontent.com/45051549/98753396-ebb8f600-23cc-11eb-862d-a48ad640b67f.png)

**Comment by ciro-unity** [comment]
Wasn't this bug fixed?
Are you using the very latest version of the game?

In any case, we won't have Terrain in the game so I think the current implementation is satisfactory, and the player cannot climb very steep surfaces.
Or maybe they can now, with the new implementation of the state machine?

I'll keep the bug open so we have an eye on it.

**Comment by antoniucraciun** [comment]
I tested it on main branch and state-machine-improvements branch and the unity version is 2019.4.11f1. I attached below 2 short recordings.

![branch_main](https://user-images.githubusercontent.com/45051549/98877012-2d5aa700-2488-11eb-9e19-990081a8bbac.gif)
First one is from 'main' branch.
![branch_state_machine_improvements](https://user-images.githubusercontent.com/45051549/98877207-9d692d00-2488-11eb-8ef8-efcaef4dee7d.gif)
Second one is from 'state-machine-improvements' branch.

**Comment by ciro-unity** [comment]
Ah, thanks for the info. So it's happening more on the`state-machine-improvements` branch?

We're still working on that, so I'd hold off in "fixing" the bug, but as I said I'll keep this ticket open to remind ourselves.

**Comment by ciro-unity** [comment]
Saw the issue even on `main`. I see how it is: you can climb if you spam the button, because you probably never enter the JumpDescending state, so you can't go into Sliding.

Can be probably fixed by editing the State Machine flow, so we'll do it once the State Machine is more done.

**Comment by GFX5000i** [comment]
The problem seem to be the order of the state transitions in the **Walking** state. Since the state machine evaluates the transitions in order, **JumpAscending** is evaluated before **Sliding**.

Moving the Sliding transition to first seems to solve the issue.

For future reference to the documentation, when creating a transition table:
- The transition priority goes from top do bottom.
- Give priority to transitions that break the player's flow like Sliding, taking damage, etc.
- Then check for important transitions like jumping and attacking.
- Lastly check for smaller transitions like idle.

**Comment by ciro-unity** [comment]
Great find, @GFX5000i!
