### ISSUE TITLE
Settings.json still shows up on GitHub Desktop even though it's ignored

### ISSUE THREAD

**Issue by GordonArber** [UnityTechnologies/open-project-1#176]
**Short description**
UOP1_Project\ProjectSettings\Packages\com.unity.probuilder\Settings.json still appears in the GitHub Desktop changes every time the project is open even though "ProjectSettings/Packages/com.unity.probuilder/Settings.json" is in the .gitignore file.

**Expected behaviour**
I expect the Settings.json file to be ignored by GitHub Desktop.

**To Reproduce**
1. Open UOP1_Project in Unity
2. Click on Play button
3. Open GitHub Desktop
4. See the "UOP1_Project\ProjectSettings\Packages\com.unity.probuilder\Settings.json" files listed as one of the changed files.

**Comment by ciro-unity** [comment]
I know, I think it's because in Git once a file is tracked, it will be even if it's subsequently included in the .gitignore. You need a specific Git command to make Git forget the file. I'll look into it when I have time!

**Comment by GordonArber** [comment]
Oh Ok.
No worries, I just wanted to make sure it was brought up. :)

**Comment by treivize** [comment]
> I know, I think it's because in Git once a file is tracked, it will be even if it's subsequently included in the .gitignore. You need a specific Git command to make Git forget the file. I'll look into it when I have time!

I think you refer to this command:
`git rm --cached <file>`

**Comment by ciro-unity** [comment]
Thanks @treivize. Should be fixed on `main` now. Let me know if you see it again, otherwise I'll close it in a couple of days.

**Comment by GordonArber** [comment]
> Thanks @treivize. Should be fixed on `main` now. Let me know if you see it again, otherwise I'll close it in a couple of days.
> 
> And thanks @GordonArber for reporting it!

This seems like it's working on my end.

**Comment by ciro-unity** [comment]
Perfect, thanks for checking @GordonArber!
I'll close it then.
