### ISSUE TITLE
[Wiki] Modified Object-Pooling.md

### ISSUE THREAD

**Issue by davejrodriguez** [UnityTechnologies/open-project-1#196]
- Removed IPoolable references from diagram and code examples.
- Renamed MyPoolableComponent to MyComponent in example code to reflect that any component (really any object) can now be pooled.

https://hastebin.com/ufiriqogiq.md

**Comment by ciro-unity** [comment]
Thanks! I've put it in!
https://github.com/UnityTechnologies/open-project-1/wiki/Object-Pooling

The only changes I made is that I removed the link to the ToC inside the ToC, and added a link to the Factory page where we mention factories.
