### ISSUE TITLE
Objects are black when the scene lighting is not baked

### ISSUE THREAD

**Issue by ciro-unity** [UnityTechnologies/open-project-1#206]
**Short description**
All objects (both dynamic and static) are black when dragged into a new scene.

**Expected behaviour**
Object should "work" automatically when dragged into a new scene.

**To Reproduce**
1. Create a new scene.
2. Drag any object from the `/Prefabs` folder (e.g. a character).
3. Observe that the object is black.

**Notes**
- Generating lighting, even if not the Baked GI, fixes the object. The object is probably becoming black due to missing ambient light information.

![image](https://user-images.githubusercontent.com/20049224/99889410-128ced00-2c55-11eb-8c1b-ccce0ce3d4d4.png)

**Comment by Tatranskymedved** [comment]
I've just downloaded fresh repo, on Main branch I cannot reproduce this behaviour.

![image](https://user-images.githubusercontent.com/2912979/99910321-909cd280-2ced-11eb-9018-5cace8842715.png)

**Comment by Tatranskymedved** [comment]
I'm not that experienced in Unity so I'm trying my best by test-failure errors, I'm warning that my founding might not be clear/make sense :wink: :

For dynamic objects: we're using Skinned Mesh Renderer which doesn't support lightmap (they will be always dark without direct light?) - https://forum.unity.com/threads/problem-with-skinned-mesh-renderer.366293/

However I've played around with static objects, I've found that when I've set constant `color` in shader to value `1` (Shaders/CustomHLSL/CustomLighting.hlsl), objects get proper color. I assume that the light at the position of that object has wrong color (black?) and thus it doesn't enlighten it.

I'd like to follow up on fix, but I would need some more hint what can be wrong & what to check. Thanks.

**Comment by ciro-unity** [comment]
Hey @Tatranskymedved! Welcome to the project :)
Have you followed the exact steps?

For clarification, when I say dynamic objects I mean not static. But they don't need to be `SkinnedMeshRenderer`s. Both `SkinnedMeshRenderer` and `MeshRenderer` create the issue.

**Comment by Tatranskymedved** [comment]
Hi @ciro-unity , I've added PR, once you have little time, could You please review it & confirm if we want to do it this way and if we want light on all objects or just the static/with Baked GI? Thanks!

**Comment by treivize** [comment]
@Tatranskymedved, regarding this issue, I think that the smallest impact needed to fix it without having to use branch should be:

![image](https://user-images.githubusercontent.com/42570903/104173072-89e52e80-5405-11eb-92d6-8471960e5f57.png)

(Backed GI) -> (one minus) -> (Step with edge to 1) will out 1 only if Baked GI will be zero and out 0 for any other value. So adding this value to the initial Backed GI node will force Backed GI to return a default value (1) if Backed GI is not defined.

Result from a brand new Default Scene:
![image](https://user-images.githubusercontent.com/42570903/104173567-4939e500-5406-11eb-9b24-ec58aa6dcc00.png)
