### ISSUE TITLE
[Enhancement] Localization Support for UI

### ISSUE THREAD

**Issue by Allstreamer** [UnityTechnologies/open-project-1#234]
There needs to be localization Support for UI Text so interfaces and later options can be translated!

**Comment by ciro-unity** [comment]
Yes, we will have localisation in the project, we talked about it in [livestream #3](https://youtu.be/0lhLLnKitSI?t=3939). We'll enable it on the UI when we have a proper UI.

Closing this one since it's not really an issue.
