### ISSUE TITLE
Character gets occluded by the environment

### ISSUE THREAD

**Issue by SundarakrishnanN** [UnityTechnologies/open-project-1#24]
**Short description**
Sometimes the obstacles covers the player and hence the player is not seen in the camera(cinemachine) and instead only the obstacle is seen,...

**Expected behaviour**
The expected result is to  view the player at all times and even if there are obstacles we should view our player only...The cinemachine must align itself in such a way that the player is seen instead of obstacles..

**Fix**
The fix for the bug is simple, and I downloaded a clone of the project and fixed it..I would love to fix it officially on the original project with your permission..Hoping for a reply if I can implement the same...
**Notes**
![image](https://user-images.githubusercontent.com/72200790/94819425-df7c6900-041c-11eb-9591-502a44fe01c3.png)
![image](https://user-images.githubusercontent.com/72200790/94819491-f753ed00-041c-11eb-9519-6c2c5768c2f0.png)

Above are two screen shots to demonstrate the bug..As you can see in the screen shots , the player is not seen as it is covered by the obstacles...I would be very glad to fix the bug in the original version with your permission..

**Comment by ciro-unity** [comment]
Hi, I think it's a valid bug even though I was hoping to fix it later once we know better how the environment looks like. I think there's no way to fix it, but rather you change the behaviour of the camera.

So for now I think we should leave it open and come back to this later.
I also changed the title of the issue, the previous one (_Bug In The Cine-machine Controller_) wasn't descriptive of what the bug actually is.

Out of curiosity, what would be your solution?

**Comment by Quickz** [comment]
> Hi, I think it's a valid bug even though I was hoping to fix it later once we know better how the environment looks like. I think there's no way to fix it, but rather you change the behaviour of the camera.
> 
> So for now I think we should leave it open and come back to this later.
> I also changed the title of the issue, the previous one (_Bug In The Cine-machine Controller_) wasn't descriptive of what the bug actually is.
> 
> Out of curiosity, what would be your solution?

I can throw in a couple of random ideas if moving the camera isn't an option:

Options1:
Make any object that obscures the view of the player character slightly transparent.

Options2:
Have the game render a silhouette of the player character through the objects that obscure him.

For a reference here's a screenshot of a game called Overwatch where a character is using an ability which allows her to see enemies (The red silhouettes) through walls.
![reference](https://user-images.githubusercontent.com/17292064/94862744-12852380-0442-11eb-9c4a-f8526f0630ea.png)

**Comment by dyoxyne** [comment]
Another solution could also be [Cinemachine Collider](https://docs.unity3d.com/Packages/com.unity.cinemachine@2.3/manual/CinemachineCollider.html) extension.
It will however affects the camera behavior (but it is pretty common in 3rd person platformer games).

**Comment by ElgenTidwell** [comment]
I would like to help fix this issue using a dynamic system that works with any type of environment.

**Comment by SundarakrishnanN** [comment]
> Hi, I think it's a valid bug even though I was hoping to fix it later once we know better how the environment looks like. I think there's no way to fix it, but rather you change the behaviour of the camera.
> 
> So for now I think we should leave it open and come back to this later.
> I also changed the title of the issue, the previous one (_Bug In The Cine-machine Controller_) wasn't descriptive of what the bug actually is.
> 
> Out of curiosity, what would be your solution?

Hi,
My solution would be to use the extension(Cine-machine Collider) and I would tweak a few values in the same(to make it better and smooth).
I have tried the same in the clone of the project and it is working fine.....I would like to do it sir....A  lot of them are also volunteering to solve the bug, but I would like to solve this bug... A lot of requirements in the game, doesn't seem that suited to me...Hence, I searched if there was any bug which I could solve and I found this.. I would be glad to show a fix to this bug(which is perfectly of my level, compared to other required tasks right now).Also I will look into other possible solutions until I receive 
 a reply.(but the above mentioned method would be my preferred solution) Hoping for a reply on whom the project is assigned...
Thank you,
Sundarakrishnan N

**Comment by SundarakrishnanN** [comment]
> I would like to help fix this issue using a dynamic system that works with any type of environment.

No , please dont work on it , I already found a fix...

**Comment by Sposito** [comment]
> No , please dont work on it , I already found a fix...
Hey @SundarakrishnanN how familiar are you with working collaboratively on projects like this? You can always open a PR with your changes so people can comment on your solution even if it isn't meant to get in right away. Feel free to ping me if you wanna talk about it.

**Comment by SundarakrishnanN** [comment]
> > No , please dont work on it , I already found a fix...
> > Hey @SundarakrishnanN how familiar are you with working collaboratively on projects like this? You can always open a PR with your changes so people can comment on your solution even if it isn't meant to get in right away. Feel free to ping me if you wanna talk about it.

Hi, @Sposito  I am not at all familiar with working on GitHub...So could you please help me out with how I can implement the changes on the original version...I downloaded a clone of the project and I fixed it...There were no changes to the scripts, there were changes to the Cine-machine.. Please help me out in proceeding further..
Thank you

**Comment by MileyHollenberg** [comment]
> Another solution could be [Cinemachine Collider](https://docs.unity3d.com/Packages/com.unity.cinemachine@2.3/manual/CinemachineCollider.html) extension.
> It will however affects the camera behavior (but it is pretty common in 3rd person platformer games).

This would be my way of fixing this issue as well

**Comment by MEGATANK58** [comment]
Is anyone working on this yet? I wanna work on this

**Comment by SundarakrishnanN** [comment]
> Is anyone working on this yet? I wanna work on this

Hey, I have fixed this issue in a clone of the project but since I am not yet assigned by unity,I am not sure how I can implement the changes in the official project(I am new to GitHub, I would be glad if someone helped me by explaining about GitHub and how I can implement the changes done in the clone of the project in the official version)..
Thank you

**Comment by SundarakrishnanN** [comment]
How do I create a pull request for this? How do I show my fix to Unity ?(I have fixed it in a clone of the project) Please help me.I am new to GitHub..
Thank you,

**Comment by MEGATANK58** [comment]
> > Is anyone working on this yet? I wanna work on this
> 
> Hey @MEGATANK58  , I have fixed this issue in a clone of the project but since I am not yet assigned by unity,I am not sure how I can implement the changes in the official project(I am new to GitHub, I would be glad if someone helped me by explaining about GitHub and how I can implement the changes done in the clone of the project in the official version)..
> Thank you

Just open a PR on the Pull Request page (near Issues) on GitHub page of this repository and click New PR then upload all the files

**Comment by SundarakrishnanN** [comment]
> > > Is anyone working on this yet? I wanna work on this
> > 
> > 
> > Hey @MEGATANK58  , I have fixed this issue in a clone of the project but since I am not yet assigned by unity,I am not sure how I can implement the changes in the official project(I am new to GitHub, I would be glad if someone helped me by explaining about GitHub and how I can implement the changes done in the clone of the project in the official version)..
> > Thank you
> 
> Just open a PR on the Pull Request page (near Issues) on GitHub page of this repository and click New PR then upload all the files,i too am working on this right now

thanks for the reply,should I upload the entire Unity project folder present locally on my system? What is the Base : Master and Compare: Master ? From the day since I opened this issue I am struggling to upload the fix.
Thank you

**Comment by SundarakrishnanN** [comment]
Hey, @ciro-unity 
I am not able to create a pull request here , so I committed the fix in the fork of the project 
Link to the Fix : https://github.com/SundarakrishnanN/open-project-1/commit/fe02b890f437790cf928dea0bb9370923e719127
Is this enough? Is the solution good enough? How else should I proceed to make the changes in the original version?
Thank you,

**Comment by MEGATANK58** [comment]
@SundarakrishnanN  Publish your current files to your fork using GitHub desktop then to go your repository you should see something like this: 
![image](https://user-images.githubusercontent.com/51410502/95043004-345c0000-06f9-11eb-9fbb-df75c434b0c6.png)
Click Pull Request
![image](https://user-images.githubusercontent.com/51410502/95043062-5f465400-06f9-11eb-9301-ccf3f0b24a76.png)
And then follow the steps

**Comment by SundarakrishnanN** [comment]
> @SundarakrishnanN Publish your current files to your fork using GitHub desktop then to go your repository you should see something like this:
> ![image](https://user-images.githubusercontent.com/51410502/95043004-345c0000-06f9-11eb-9fbb-df75c434b0c6.png)
> Click Pull Request
> ![image](https://user-images.githubusercontent.com/51410502/95043062-5f465400-06f9-11eb-9301-ccf3f0b24a76.png)
> And then follow the steps

Hey @MEGATANK58 
Thanks a lot for your help..It worked!

**Comment by ciro-unity** [comment]
We can finally close this issue! Thanks to @shuttle127 in PR #220, we have a shading pass which draws characters when occluded by the scenery 🎉 
Thanks for the discussion everyone!
