### ISSUE TITLE
[Object Pool] HasBeenPrewarmed is not reset in between play sessions

### ISSUE THREAD

**Issue by davejrodriguez** [UnityTechnologies/open-project-1#242]
**Short description**
`PoolSO.HasBeenPrewarmed` is a boolean that prevents a pool from being prewarmed multiple times over its lifetime. It switches to true once `PoolSO.Prewarm()` is called. However, `PoolSO.HasBeenPrewarmed` remains true even after you exit play, so when Prewarm is called in a subsequent play session, the pool is prevented prewarming.

**Expected behaviour**
`PoolSO.HasBeenPrewarmed` should be reset to its initial value of false when exiting play mode. 

**To Reproduce**
1. Create an instance of a pool as an asset.
2. Create script that takes in a reference to a pool and call `pool.Prewarm(10)` in its `Awake` or `Start` method.
3. Attach the script to a GameObject in scene and set the pool reference to the pool asset you created.
3. Press play.
4. Exit play mode.
5. Press play again.
6. Notice you get a warning saying the pool has already been prewarmed, but no objects were created as members of that pool.

**Notes**

Should be an easy fix. Just need to reset `HasBeenPrewarmed` to false in the `OnDisable` method of `PoolSO`.

**Comment by ciro-unity** [comment]
Ah! That's why! I was going nuts trying to understand why it was verified as `true`, it makes sense... it's part of the SO! 🤦🏻

**Comment by davejrodriguez** [comment]
Yeah, my bad. That was an oversight when I added the check. The fact that playmode changes persist on SO assets is a bit of a double-edged sword 😄
