### ISSUE TITLE
LocationSO not serialized properly

### ISSUE THREAD

**Issue by rainaldisatria** [UnityTechnologies/open-project-1#257]
**Short description**
LocationSO doesn't serialize some of it fields.

**Expected behaviour**
LocationSO should serialize all of it fields.

**To Reproduce**
1. Go to ScriptablesObjects/SceneData/Locations
2. Click on any of LocationSO. Let say Beach.
3. Add Music reference to the selected LSO.
4. Deselect the selected LSO.
5. LSO is not serialized. Music is from the reference is gone.

**Comment by ciro-unity** [comment]
Nice find! Not super urgent to fix, but it can be a nice first task for somebody!

**Comment by ciro-unity** [comment]
LOL ok nevermind, I didn't see you already put the fix in a PR :)
So fast :)
