### ISSUE TITLE
Build Fail Due To SceneAccessTool and SceneAccessHolderSO Errors

### ISSUE THREAD

**Issue by davejrodriguez** [UnityTechnologies/open-project-1#270]
**Short description**
Building a player fails with errors caused by SceneAccessTool and SceneAccessHolderSO.

**Expected behaviour**
I'd expect this editor tool to be put in an `Editor` folder so it does not get included with the build and cause errors when it can't find its UnityEditor types :)

**To Reproduce**
1. Try to build player.
2. Frown when it fails due to errors with the SceneAccessTool and its related SceneAccessHolderSO.

**Notes**
Some sample errors (they all have to do with missing editor assemblies):
- `Assets\Scripts\EditorTools\SceneAccessTool.cs(4,7): error CS0246: The type or namespace name 'UnityEditorInternal' could not be found (are you missing a using directive or an assembly reference?)`
- `Assets\Scripts\SceneManagement\ScriptableObjects\SceneAccessHolderSO.cs(12,31): error CS0246: The type or namespace name 'PropertyDrawer' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by amel-unity** [comment]
Thanks for testing @davejrodriguez ! The PR from @ThomasChen1220 fixes the issue, I will merge it now
