### ISSUE TITLE
SceneAccessTool: Scene file not found

### ISSUE THREAD

**Issue by davejrodriguez** [UnityTechnologies/open-project-1#271]
**Short description**
When using the SceneAccessTool, I get an ArgumentException: Scene file not found. The path it thinks the scene is at looks to be an absolute path to the scene _on someone else's computer_. So it seems the path is being cached in the SceneAccessHolderSO and needs to be refreshed so other developers will get the correct path on their machines.

**Expected behaviour**
I'd expect the scene list to be refreshed with scene paths from _my_ computer.

**To Reproduce**
1. Open the Scene Access Tool.
2. Click any of the scenes.

**Notes**
- `ArgumentException: Scene file not found: 'D:\indie\_OnGoing\open-project-Unity\UOP1_Project\Assets\Scenes\Menus\MainMenu.unity'.`

**Comment by ThomasChen1220** [comment]
in this thread: https://forum.unity.com/threads/editor-window-to-open-scenes.1019986/#post-6633193
dotsquid mentioned a solution for this by using EditorPrefs. 
Right now I'm not sure whos version of the tool will be used in the game. I'll wait until the PR regarding GameSceneSO is sorted out to see what to do about this.

**Comment by ciro-unity** [comment]
Thanks for the thorough testing, @davejrodriguez !

**Comment by amel-unity** [comment]
Thanks again for testing @davejrodriguez , I will need to close this issue because we just merged [another PR](https://github.com/UnityTechnologies/open-project-1/pull/285) to replace this tool as [mentioned in the thread](https://forum.unity.com/threads/editor-window-to-open-scenes.1019986/#post-6713191).
