### ISSUE TITLE
Project should use latest release of 2019.4

### ISSUE THREAD

**Issue by tacman** [UnityTechnologies/open-project-1#28]
**Short description**
The base project should be the latest release of 2019.4.  That way, new users aren't prompted to update the project:

![image](https://user-images.githubusercontent.com/619585/94858923-bef2e580-0401-11eb-8b83-2ac4d8e054a4.png)

**To Reproduce**
Clone and open.

**Comment by luisquid** [comment]
Isn't the project already on 2019.4.7?

**Comment by tacman** [comment]
Yes, my bad.  I don't fully understand the versioning in Unity, but that's
irrelevant, since the Contributions Guidelines explicitly exclude library
versions.

Hoping to find some other way to contribute!

**Comment by luisquid** [comment]
Hey, thank you so much for wanting to contribute! 
I'm sure with the help of everyone something great will come out out of this. 
It would be cool if you could close the issue as to not clutter the issues list :D
