### ISSUE TITLE
Permanent loss of input control and null refs after interacting with a dialogue target

### ISSUE THREAD

**Issue by davejrodriguez** [UnityTechnologies/open-project-1#280]
**Short description**
In NewInteractionExample and InteractionExample, interacting (E on keyboard) with the Bard Hare disables controls and throws NullReferenceExceptions in the InputReader when triggering the Dialogues/MoveSelection action.

**Expected behaviour**
I imagine movement controls are supposed to be disabled. However, no dialogue is presented, so there is no avenue for returning to an enabled movement. I'd expect there to be some dialogue and movement control be returned to the player once the dialogue has finished.

**To Reproduce**
1. Play NewInteractionExample or InteractionExample
2. Walk up the Bard Hare.
3. Trigger the interact action (E on keyboard)
4. Try to walk away or move camera.

**Notes**
- `NullReferenceException while executing 'performed' callbacks of 'Dialogues/MoveSelection[/Keyboard/w,/Keyboard/s,/Keyboard/a,/Keyboard/d,/Keyboard/upArrow,/Keyboard/downArrow,/Keyboard/leftArrow,/Keyboard/rightArrow]'`
- `NullReferenceException: Object reference not set to an instance of an object
InputReader.OnMoveSelection (UnityEngine.InputSystem.InputAction+CallbackContext context) (at Assets/Scripts/Input/InputReader.cs:127)`

![image](https://user-images.githubusercontent.com/1964335/103051030-c985cc80-4563-11eb-8f45-6f521776029d.png)

**Comment by davejrodriguez** [comment]
I've found that this behavior and the corresponding errors happens in any scene with an interaction. The interactions in CutsceneExample, to its credit, returns control after the cutscene has finished.

**Comment by rainaldisatria** [comment]
Loss of input control should be fixed after this PR is merged: https://github.com/UnityTechnologies/open-project-1/pull/195
It happen when trying to call empty UnityAction

**Comment by ciro-unity** [comment]
Is this still happening? (might be)

**Comment by rainaldisatria** [comment]
Now that we are using delegate, I don't think so.

But I found another bug (minor) while trying to check this...
I'll open a new PR.

**Comment by ciro-unity** [comment]
I am seeing it again, and consistently... (every time I play, and with **exactly** the same timing)
Aaaaaaahhh what is it?! 😭

**Comment by amel-unity** [comment]
Hey everyone! 
This issue has been fixed so I will close it just to avoid that anyone spends time looking into fixing it. 
Thank you all :)
