### ISSUE TITLE
PoolSO spams console with prewarm warning

### ISSUE THREAD

**Issue by Bvanderwolf** [UnityTechnologies/open-project-1#289]
**Short description**
After entering playmode after starting Unity, The PoolSO script warns you each time on awake that the "Pool SoundEmitterPool has already been prewarmed".

**Expected behaviour**
The scriptable object should reset its state using the OnDisable function making sure this warning only occurs when necessary.

**To Reproduce**
1. Enter PlayMode with AudioManager in the scene
2. Exit Playmode with AudioManager in the scene
3. Re-Enter Playmode with AudioManager in the scene

**Notes**
Screenshot:
![image](https://user-images.githubusercontent.com/34794758/103553272-843f9400-4ead-11eb-80ab-d725d2f822f4.png)

I already found a way to fix this problem which is simple adding one line to the PoolSO script:
![image](https://user-images.githubusercontent.com/34794758/103553524-daacd280-4ead-11eb-8a0c-fa9a37cfd2c5.png)

**Comment by davejrodriguez** [comment]
Hey, are you sure you've pulled the latest changes from main? I believe this was fixed in #243

**Comment by Bvanderwolf** [comment]
Shoot, you are right!
