### ISSUE TITLE
Weird sliding effect on Mesh/Sphere Collider

### ISSUE THREAD

**Issue by i1qwert** [UnityTechnologies/open-project-1#293]
**Short description**
Weird buggy sliding effect when jumping on surfaces with Mesh/Sphere collider on them.

**Expected behaviour**
A regular fall and nothing much.

**To Reproduce**
1. Open TestingGround scene, play it
2. Go to any of central rocks
3. Jump on them while pressing W
4. Release jump key and just move left/right/forward

**Notes**
On central rocks:

https://user-images.githubusercontent.com/35143793/103897578-5fa22100-5126-11eb-8b03-3f7ed7269d50.mp4

On sphere collider:

https://user-images.githubusercontent.com/35143793/103897708-85c7c100-5126-11eb-9a2b-8ff1f1af3cbf.mp4

Also you can stuck on surfaces with jump not working there:

https://user-images.githubusercontent.com/35143793/103897811-a4c65300-5126-11eb-828b-8f4d7b4e56dd.mp4

**Comment by ciro-unity** [comment]
Oh no, more climbing bugs :D
Thanks for reporting it. For now I consider it minor as it doesn't disrupt the gameplay.
