### ISSUE TITLE
StateMachine Wiki

### ISSUE THREAD

**Issue by DeivSky** [UnityTechnologies/open-project-1#295]
Long-awaited, [here's the documentation of the StateMachine](https://github.com/DeivSky/open-project-1/blob/state-machine-docs/UOP1_Project/Assets/Scripts/StateMachine/documentation.md).

Any suggestions are welcomed.

**Comment by treivize** [comment]
Hi DeivSky,

thanks for this first detailed documentation on the state machine 👍 
 
Here is my suggestions following the latest comment from the forum:
- Add actions association to the state from the transition table
- Add actions from State SO inspection instead from the table. It is especially useful for states only defined as a dead end (they are not listed in the table so it is not possible to associate actions to them from the table editor)

**Comment by DeivSky** [comment]
Hey, @treivize!
Don't thank me, it was long overdue 😄.

Yes, I saw those points on the forums. I'll be making a few changes based on them soon.
I meant suggestions about the documentation, though, as that's the only purpose of this issue.

**Comment by treivize** [comment]
Oh, but I was not asking for code improvements here, maybe I miss it in the current documentation, but I am not sure it is explained how to associate actions to a state. It was just my suggestion for the documentation (explain how to do it from the table or from the state SO)

**Comment by DeivSky** [comment]
Oh, my bad! You're right, I'll be adding those comments to the docs. I will still be making changes because I don't like not being able to access a dead-end state from the transition table.

**Comment by ciro-unity** [comment]
Hey, that's great!
I made some suggestions, implemented them by doing a PR to your fork. When you're ready you tell me and I'll put it in the wiki.

It's also ok if it's not 100% finished, I'd rather have it sooner, it could be helpful to somebody exploring the project these very days. We can obviously add to it later, but it's pretty good as it is already.

**Comment by Eyap53** [comment]
Just took a look, and try to implement it without looking at the code : It worked perfectly first try, well done !

You may add an end note that the MonoBehaviour needed to make it work on a gameObject is called `StateMachine` (but I agree that it's not hard to find :) )

**Comment by DeivSky** [comment]
> Hey, that's great!
> I made some suggestions, implemented them by doing a PR to your fork. When you're ready you tell me and I'll put it in the wiki.
> 
> It's also ok if it's not 100% finished, I'd rather have it sooner, it could be helpful to somebody exploring the project these very days. We can obviously add to it later, but it's pretty good as it is already.

I've merged your changes and made a couple more based on the suggestions here. I'd say it's ready for publishing! If anything, as you say, we can edit it later 😉

**Comment by ciro-unity** [comment]
Perfect. Thanks!
I implemented it here: https://github.com/UnityTechnologies/open-project-1/wiki/State-Machine

I guess I can close the issue? Can you reopen it yourself? (I'm thinking in case we want to "recycle" it for changes on the docs)

**Comment by DeivSky** [comment]
I don't think I can, I don't see any option for it in another closed issue I opened. Anyone can comment on closed issues, though, so if anything you'll receive a notification and get to reopen it yourself? 😄

**Comment by ciro-unity** [comment]
I'll keep an eye on it, unfortunately I have a tendency to miss notifications of comments on closed PRs/issues because my notification centre is always full of stuff.

By the way I added images to it (and thus, made another couple of tweaks)
