### ISSUE TITLE
SceneLoader builds every growing list of _persistentScenes

### ISSUE THREAD

**Issue by shootingdux** [UnityTechnologies/open-project-1#302]
**Short description**
When the user loads different menus and scenes the _persistentScenes list grows as shown in image.

![image](https://user-images.githubusercontent.com/65027774/104319267-8a022e80-54d8-11eb-912a-8830c0232d51.png)

**Expected behaviour**
The _persistentScenes List<GameSceneSO> to only add values if not already present.

**To Reproduce**
1. Add a breakpoint to the LoadLocation(GameSceneSO[] locationsToLoad, bool showLoadingScreen) method of the SceneLoader.cs class
2. Run the Beach scene
3. Move the player to load the Forest scene
4. The breakpoint should trigger, at this point you can see the list of _persistentScenes
5. Repeat steps 3,4 and you will see the list of _persistentScenes grow with the same values.

**Notes**
- Currently only LoadLocation is used but when LoadMenu is used this could lead to the Gameplay scene remaining loaded as the _persistentScenes list will not be cleared.

**Comment by amel-unity** [comment]
Hi @shootingdux, I just saw your issue after I fixed it [in the last commit ](https://github.com/UnityTechnologies/open-project-1/commit/4d431bbafad551aeedb37019fcb2ee11d69565b2). Thank you for testing :)

**Comment by shootingdux** [comment]
Nice, good fix.

Closing now as it is resolved.
