### ISSUE TITLE
Trying to use an item again will cause an ArgumentOutOfRangeexception exception

### ISSUE THREAD

**Issue by kira0x1** [UnityTechnologies/open-project-1#304]
**Short description**
After an item has been used, the id is set to -1, the player can still press the button, and if they do they will get an 
ArgumentOutOfRangeexception

**Expected behaviour**
To make sure the index is not negative.
To check if the index is approriate I,E not -1 for an array.

**To Reproduce**
1. Start the initialization scene.
2. Start the game as usual
3. When loaded in go to the inventory, click an item, use it.
4. After using the item, click the button once more.
5. Then you will get the exception

**Notes**
![image](https://user-images.githubusercontent.com/13779328/104366619-b8105e80-552a-11eb-8976-4dc8a128243e.png)

**Comment by amel-unity** [comment]
Thank you @kira0x1 for testing and providing the fix, I will merge it 👍 
I think we can add later another improvement: We make the button interactable only when we have an item that could be used (For now we can still click on the use button, even though it doesn't do anything. So it can be a bit confusing for users to click without anything actually happening :) )

**Comment by kira0x1** [comment]
No worries ❤ it was just one line of code but I was worried the bug would annoy people especially ones new to the project.
This must be my smalled pr to date hehe.
