### ISSUE TITLE
Objects moved by ClickToPlaceHelper tool aren't detected in the scene so cannot be saved

### ISSUE THREAD

**Issue by Maximetinu** [UnityTechnologies/open-project-1#305]
**Short description**
If you move an object with the ClickToPlaceHelper tool, its changes are not detected by Unity, so it doesn't allow to save the scene.

**Expected behaviour**
When moving the transform, the scene name above the hierarchy should be shown as MyScene* - stating that the scene has some changes on it, so it can be saved.

**To Reproduce**
1. Go to any location scene. For example: Forest.unity
2. Select 'Location 01' Game Object
3. In the Inspector, click the button 'Place at Mouse cursor' under the 'Click to Place' component
4. Place the object anywhere around the scene
5. Unity doesn't detect any change in the scene, so it doesn't show the scene as modified.
6. As a side effect, if you save the scene with the shortcut Ctrl + S, it won't be actually saved
7. Another side effect is that you cannot perform Ctrl + Z to return the object to its original position

https://user-images.githubusercontent.com/16073309/104380056-52b86f80-5522-11eb-9b71-be7384b0cbe8.mp4

**Comment by Maximetinu** [comment]
I opened a PR for addressing this - #306

**Comment by amel-unity** [comment]
Thanks a lot for testing and proposing the fix @Maximetinu, I will merge the fix now 👍
