### ISSUE TITLE
Incorrect summary of BoolEventChannelSO

### ISSUE THREAD

**Issue by seoyeon01** [UnityTechnologies/open-project-1#308]
**Short description**
In "BoolEventChannelSO.cs" line 5~6
Instead of "BoolEventChannelSO", summary of "IntEventChannelSO".

**Comment by amel-unity** [comment]
Hey @seoyeon01 ! Thanks for mentioning it, I just updated it [on the last commit](https://github.com/UnityTechnologies/open-project-1/commit/28541fd7472cb23a6725335fdad36d8d52533386)
