### ISSUE TITLE
Can we make labels for features?

### ISSUE THREAD

**Issue by ErikBehar** [UnityTechnologies/open-project-1#34]
This would help to better track PR's that are different implementations of same feature, ie sort by label  ... 
for example we have multiple PRs for: slope bug, spawn system, state machine system

**Comment by MileyHollenberg** [comment]
I think having labels for each feature will become tedious and too granular. Having labels for types of PRs like Bugfix, Feature, Models, Textures, Sound, UI and such could be more useful.

As for the duplicate PRs, we're still looking in to how best to handle that situation but we'll update the community once there's a plan for that

**Comment by ciro-unity** [comment]
Agree with Miley. As the feature count grows, it will become a nightmare to handle and we will have labels that become unused - but still show up in the list.

Thanks for the suggestion though!
