### ISSUE TITLE
Interaction System doesn't follow the FSM

### ISSUE THREAD

**Issue by DeivSky** [UnityTechnologies/open-project-1#342]
**Short description**
Interactions don't happen along with their corresponding States (objects get picked up without the character being in the PickUp state, dialog starts without being in the Talking state, etc).

**Expected behaviour**
Drops get picked up when entering the PickUp state, dialogues start when entering the Talking state, cooking starts when entering the cooking state.

**To Reproduce**
1. Go to the InteractionExample scene, or kill any critter so it drops items.
2. Get close to an item on the ground.
3. Jump or Attack and then press the interact button
4. The item gets picked up while the character is mid-air/mid-attack, but the character never enters the PickUp state so it allows the player to skip the pick-up animation.

**Notes**
- Video of the bug:
<video src="https://user-images.githubusercontent.com/27371812/106408983-4be49480-641e-11eb-9a73-7399edc88bef.mp4" controls="controls" class="d-block rounded-bottom-2 width-fit" style="max-height:640px;"></video>

- Same thing goes for Talking and Cooking, the dialogue/cooking UI will pop up but the animations won't start since we don't get to transition into their states.

**Comment by rainaldisatria** [comment]
This is it, the problem I'm facing when developing my hack and slash game with our State Machine.
It is really hard to maintain and sync two different state machine at the same time, so what I do is: 

Removing Unity's State Machine (Animator) completely.
![image](https://user-images.githubusercontent.com/57592497/106443715-64e95600-64af-11eb-807a-33ec5a643930.png)

Then, to get the ability to transition smoothly' through one animation to another is by using CrossFadeAlphaInFixedTime();
I make an Action for that called 'PlayAnimationActionSO' that'll play the animation OnStateEnter smoothly.
![image](https://user-images.githubusercontent.com/57592497/106444092-de814400-64af-11eb-8522-ab4ca35c1d64.png)
*ignore the error line there, I have slightly different code base.*

The only catch is that we need to manually assign the Transition Duration. 
Usually the transition duration is 0.25f tho.
![image](https://user-images.githubusercontent.com/57592497/106444199-0375b700-64b0-11eb-8b7b-7b675869e83c.png)

If you want to see the working example, you can check it out here:
https://www.youtube.com/watch?v=RouJPWyfP0Y
*(it also an open source project)*

**Comment by DeivSky** [comment]
Hmm, that isn't really the problem I'm describing. I don't think we're having any issues with syncing the StateMachine and the Animator controller, the problem is the Interaction System that is working independently of them. 

For instance, we can't go from JumpAscending to PickUp because it wouldn't make sense to play the PickUp animation mid-air, so that part is working fine. However, the Interaction System doesn't care about the current state, so if you try to pick something up while jumping, you will pick it up, even though the FSM doesn't allow it.

Hope that's a better explanation.

**Comment by rainaldisatria** [comment]
Oh, well... :D
I've been very busy doing my errands lately, I didn't even read the description.
Just kinda assume it by the title 
hahaha, my bad

**Comment by AlexandreGheraibia** [comment]
Porposal :
Add the following function to interaction Manager

`public void EnableInteraction(bool enabled) {
		if (enabled)
		{
			_inputReader.interactEvent += OnInteractionButtonPress;
		}
		else
		{
			_inputReader.interactEvent -= OnInteractionButtonPress;
			
		}
	}`
And create an Action DisableInteraction

**Comment by AlexandreGheraibia** [comment]
I think they are in sync but the object in pickup is destroyed when the interaction is initiated in interactionManger

**Comment by ciro-unity** [comment]
@AlexandreGheraibia double check the opening post, it's not like they are "never" in sync, but you can de-synch them by pressing buttons with a specific timing.

**Comment by DeivSky** [comment]
Okay I've changed the title because "sync" usually refers to animations, but I want to stress that the problem is the Interaction System.

> I think they are in sync but the object in pickup is destroyed when the interaction is initiated in interactionManger

That's exactly what I meant with "out of sync", the item is transferred to the inventory and the GO destroyed regardless of our current state.

**Comment by AlexandreGheraibia** [comment]
@DeivSky @ciro-unity my bad, I focused on pick up. But the problem is in OnInteractionButtonPress()
in interactionManager. This function informs the state machine that we have interacted and simultaneously processes the action

**Comment by DeivSky** [comment]
>This function informs the state machine that we have interacted and simultaneously processes the action

Exactly, the script is doing too many things. Kind of reminds me of the earlier versions of `Protagonist.cs`.

**Comment by AlexandreGheraibia** [comment]
we could divide the function in two add an voidEventChannel on interactionManager and raise the event in an action on talk and pickup

```
void onStateMachineResponded()
	{
		//remove interaction after press
		Interaction onGoingInteraction = _ongoingInteractions.Count > 0 ?
			_ongoingInteractions.First.Value : Interaction.NONE;
		_toggleInteractionUI.RaiseEvent(false, onGoingInteraction.Type);
		switch (onGoingInteraction.Type)
		{
			case InteractionType.None:
				return;
			case InteractionType.PickUp:
				GameObject itemObject = onGoingInteraction.InteractableObject;
				_ongoingInteractions.RemoveFirst();
				if (_onObjectPickUp != null)
				{
					//raise an event with an item as parameter (to add object to inventory)
					Item currentItem = itemObject.GetComponent<CollectibleItem>().GetItem();
					_onObjectPickUp.RaiseEvent(currentItem);
					//Debug.Log("PickUp event raised");
				}
				
				Destroy(itemObject);
				break;
			case InteractionType.Cook:
				if (_onCookingStart != null)
				{
					_onCookingStart.RaiseEvent();
					//Debug.Log("Cooking event raised");
					//Change the action map
					_inputReader.EnableMenuInput();
					//set current interaction for state machine
				}
				break;
			case InteractionType.Talk:
				if (_startTalking != null)
				{
					//raise an event with an actor as parameter
					//Actor currentActor = currentInteractableObject.GetComponent<Dialogue>().GetActor();
					//_startTalking.RaiseEvent(currentActor);
					//Debug.Log("talk event raised");
					//Change the action map
					_inputReader.EnableDialogueInput();
					//set current interaction for state machine
					
				}
				break;
			default:
				break;
		}
	}

	void OnInteractionButtonPress()
	{
		Interaction onGoingInteraction = _ongoingInteractions.Count > 0 ?
			_ongoingInteractions.First.Value : Interaction.NONE;
		//set current interaction for state machine
		if (onGoingInteraction.Type!= InteractionType.None)
		currentInteraction = onGoingInteraction.Type;
	}
```

**Comment by AlexandreGheraibia** [comment]
Result :



https://user-images.githubusercontent.com/27300700/106690876-d4a43180-65d2-11eb-8918-49932daa5591.mp4
