### ISSUE TITLE
Help me with my first step

### ISSUE THREAD

**Issue by OmarElKhatibCS** [UnityTechnologies/open-project-1#35]
Hello , I've never work on team before or already existent project.
Can some one help me with first steps?

# About Me
I am a 20 years old student , I've been programming for long time , I know how to code. Also I worked on unity but it's from 2-3 years ago. As I said I've never work on a team before.

**Comment by nslindtner** [comment]
Hi Omar

Take a look at this link: https://open.codecks.io/unity-open-project-1/decks/32

Click at the readme card - there is a lot of information. Especially the "usefull links" is pretty awesome. (I got the introduction video from that card: https://youtu.be/lYAHmthUO1M)

Happy reading .. and enjoy

**Comment by OmarElKhatibCS** [comment]
> 
> 
> Hi Omar
> 
> Take a look at this link: https://open.codecks.io/unity-open-project-1/decks/32
> 
> Click at the readme card - there is a lot of information. Especially the "usefull links" is pretty awesome. (I got the introduction video from that card: https://youtu.be/lYAHmthUO1M)
> 
> Happy reading .. and enjoy

Thanks , I am going to read it now.

**Comment by ciro-unity** [comment]
Closing it, thanks for the help @nslindtner!
Good luck @OmarElKhatibCS.
