### ISSUE TITLE
Processing for OnGameExit

### ISSUE THREAD

**Issue by seoyeon01** [UnityTechnologies/open-project-1#374]
I looked up Codecks RoadMap, Youtube, Github, and Forums,
but i couldn't find any issues regarding the end of game.(Application.Quit)

Is there a roadmap or planning card that i missed?

If i understand correctly.
- PersistentManagers have GameExitListener
- Main Menu Scene have Exit Button
- Exit Button can raised onGameExit(SO) Event
- SceneLoader's private void ExitGame() is used to exit the game

----
Current project does not have ExitGame() registered in GameExitListener's Void EventListener.
While adding SceneLoader and registering ExitGame(), 
ExitGame was not accessible from GameExitListener because it was private.

Registration of ExitGame() with external access(public) is easily resolved.
However i don't know if this is the right approach.

In addition, the ExitGame() is not processed for EditorMode.
```
/// SceneLoader.cs    ExitGame()
...
#if UNITY_EDITOR
		UnityEditor.EditorApplication.isPlaying = false;
#else
		Application.Quit();
#endif
...
```
It seems that Exit processing in Editor PlayMode should be done.

**Comment by ciro-unity** [comment]
Hey @seoyeon01!
If I understand it correctly, you're saying that the game "doesn't exit" when you press the Exit button in the Editor, right?
In reality, it does, but only in the build. The Editor never responds to `Application.Quit( );` - and you have it correct, a good substitute would be `UnityEditor.EditorApplication.isPlaying = false;`

It's not super important to have an exit button in the editor, but if you want to implement it, why don't you go ahead, make the modification, and open a PR? (you know how to do it?)

And by the way, you don't need to make `ExitGame( )` public. Look into the `OnEnable` of the SceneLoader script, you'll see how that function is wired to an event channel called OnGameExit, calling its `RaiseEvent` function. For more information: https://github.com/UnityTechnologies/open-project-1/wiki/Event-system

Soon I'll close this issue. Thanks :)

**Comment by seoyeon01** [comment]
> Hey @seoyeon01!
> If I understand it correctly, you're saying that the game "doesn't exit" when you press the Exit button in the Editor, right?
> In reality, it does, but only in the build. The Editor never responds to `Application.Quit( );` - and you have it correct, a good substitute would be `UnityEditor.EditorApplication.isPlaying = false;`
> 
> It's not super important to have an exit button in the editor, but if you want to implement it, why don't you go ahead, make the modification, and open a PR? (you know how to do it?)
> 
> And by the way, you don't need to make `ExitGame( )` public. Look into the `OnEnable` of the SceneLoader script, you'll see how that function is wired to an event channel called OnGameExit, calling its `RaiseEvent` function. For more information: https://github.com/UnityTechnologies/open-project-1/wiki/Event-system
> 
> Soon I'll close this issue. Thanks :)

Thank you.
My question has been solved perfectly :)
