### ISSUE TITLE
After jumping, player can "stick" to object above him for a short time

### ISSUE THREAD

**Issue by LHunor** [UnityTechnologies/open-project-1#38]
**Short description**
Player jumps, cancels jump before collides with object above him. In this case player only stops upward motion after gravitational force pulls him down, making it look like it got "stuck" onto the object above him.

**Expected behaviour**
Player jumps, cancels jump before collides with object above him. After the collision, the upward motion stops immediately and gravity starts pulling the player down.

**To Reproduce**
1. Go to 'CharController scene'
2. Play scene
3. Go below the floating platform in the middle
4. Press jump and release it immediately, so jump is cancelled before player's head hits the floating platform

**Fix**
In the Character.cs script, inside the OnControllerColliderHit function, the code responsible for stopping the upwards motion only runs if the isJumping flag is set to true. Thus, canceling the jump (which sets the flag to false) before the collision, the code won't run. Instead of checking the isJumping flag, we could check whether the player has any upward motion (verticalMovement >= 0). This way, the player will stop any upward motion after hitting a ceiling in any situation.

**Notes**
![sticyhead](https://user-images.githubusercontent.com/30088611/94919871-78f75980-04b5-11eb-9606-43a850e56dcf.png)

**Comment by Anmol270900** [comment]
Hi! I am a beginner at Unity and would love to work on this issue. Would be great it's assigned to me.
Thankyou.

**Comment by ciro-unity** [comment]
Huh, I thought this had been fixed by Pull Request #16? Is it the same issue? Still happening?

**Comment by LHunor** [comment]
Same issue, #16 solved it partially, but it still happens in some cases.
@Quickz 's solution:
```
private void OnControllerColliderHit(ControllerColliderHit hit)
    {
        if (isJumping)
        {
            // Making sure the collision is near the top of the head
            float permittedDistance = characterController.radius / 2f;
            float topPositionY = transform.position.y + characterController.height;
            float distance = Mathf.Abs(hit.point.y - topPositionY);

            if (distance <= permittedDistance)
            {
                // Stopping any upwards movement
                // and having the player fall back down

                isJumping = false;
                gravityContributionMultiplier = 1f;

                verticalMovement = 0f;
            }
        }
    }
```
Everything inside the `if` statement works well, the problem is with the `condition`. Releasing the jump button cancels the jump, which results in `isJumping = false`. Therefore, when the player cancels the jump before the collision and this function fires, the fix to the problem won't be executed. There are also other ways for `isJumping`  to turn false, like when the time defined in `jumpInputDuration` is exceeded, and it would result in the same behavior.
What I suggested is instead of checking `isJumping`, we should check whether the character has any upward motion:
`if (verticalMovement >= 0)`...
Very trivial change, but this way, under any circumstance if the character hits a ceiling, the function would work as intended.

**Comment by FeralPug** [comment]
Shouldn't the isJumping bool get set to false once you are back on the ground I.e. you are done jumping. Would that solve the problem. I suppose I could explore all of the code relating to the jumping.

**Comment by ciro-unity** [comment]
Oh, I see, good catch!! Seems like Quickz sent a quick fix. Let me check if it works.
