### ISSUE TITLE
No locale selected in build

### ISSUE THREAD

**Issue by ciro-unity** [UnityTechnologies/open-project-1#385]
**Short description**
When the game is built, the Localisation system fails when loading strings and presents this message in the console/log:

```No Locale could be selected:
No Locales were available. Did you build the Addressables?
The following (3) IStartupLocaleSelectors were used:
	UnityEngine.Localization.Settings.CommandLineLocaleSelector
	UnityEngine.Localization.Settings.SystemLocaleSelector
	UnityEngine.Localization.Settings.SpecificLocaleSelector

UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:LogError(Object, Object)
UnityEngine.Localization.Settings.LocalizationSettings:SelectLocale()
UnityEngine.Localization.Settings.LocalizationSettings:GetSelectedLocale()
UnityEngine.Localization.PreloadDatabaseOperation`2:BeginPreloading()
UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationBase`1:InvokeExecute()
UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationBase`1:Start(ResourceManager, AsyncOperationHandle, DelegateList`1)
UnityEngine.ResourceManagement.ResourceManager:StartOperation(AsyncOperationBase`1, AsyncOperationHandle)
UnityEngine.Localization.Settings.LocalizedDatabase`2:get_PreloadOperation()
UnityEngine.Localization.InitializationOperation:PreLoadTables()
System.Action`1:Invoke(T)
DelegateList`1:Invoke(T)
UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationBase`1:InvokeCompletionEvent()
UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationBase`1:Complete(TObject, Boolean, String, Boolean)
UnityEngine.ResourceManagement.ChainOperationTypelessDepedency`1:OnWrappedCompleted(AsyncOperationHandle`1)
System.Action`1:Invoke(T)
DelegateList`1:Invoke(T)
UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationBase`1:InvokeCompletionEvent()
UnityEngine.ResourceManagement.ResourceManager:ExecuteDeferredCallbacks()
UnityEngine.ResourceManagement.ResourceManager:Update(Single)
System.Action`1:Invoke(T)```

**Expected behaviour**
Localisation data should be loaded using the default locale EN.

**To Reproduce**
Steps to reproduce the behavior:
1. Build the game in Development mode (Build Addressable content first).
2. Start the build.
3. Notice the above error message in the Console.

**Notes**
- Localisation seems to work fine in the editor.

**Comment by IsaiahKelly** [comment]
Perhaps it would be a good idea to just remove the Localization package entirely and roll our own solution instead? This package is in early preview at the moment anyway, so issues like this are bound to happen.

Using preview packages in general also seems to completely defeat the purpose of sticking with an LTS version of Unity. One could make an exception for editor only tools, like ProGrids, since those will not affect the final build. But I do think using unreleased packages is something we should avoid whenever possible, if we actually want to keep the project as stable as possible.

**Comment by schodemeiss** [comment]
This is a known bug in Addressables. Essentially we need to ensure that the Addressable groups are using Append+Hash naming scheme.

https://forum.unity.com/threads/troubleshooting-addressables-issues.1060346/

That will fix the locales working in builds.

**Comment by ciro-unity** [comment]
>Using preview packages in general also seems to completely defeat the purpose of sticking with an LTS version of Unity.

You are right, and in this case we're taking a small gamble with this preview package. But personally I believe the package is solid, and it offers too much good functionality to pass (if you're not sold, [watch the livestream we did some time ago](https://youtu.be/KBM-T-gjiaI?t=1950)).

And in any case the fix is easy, doesn't seem to impact us in any way.
