### ISSUE TITLE
EditorInitializer does not work normally on MainMenu Scene

### ISSUE THREAD

**Issue by seoyeon01** [UnityTechnologies/open-project-1#389]
**Short description**
When start with Initialization Scene, the UI of Main Menu Scene operates normally.
(Button Click etc..)
![s1](https://user-images.githubusercontent.com/48429544/111275184-3dbea080-8679-11eb-87da-5fea5c669721.gif)

When EditorInitializer is in MainMenu Scene, UI (Button etc..) does not work normally
(You can see that the button is not pressed.)
![s2](https://user-images.githubusercontent.com/48429544/111275204-41eabe00-8679-11eb-8708-4b92ce946aa0.gif)

Disabling the EditorInitializer ensures that the UI receives input normally.
(You can see that the button can pressed.)
![s3](https://user-images.githubusercontent.com/48429544/111275834-f1279500-8679-11eb-96c4-c0250b901934.gif)
EditorInitializer is disabled and does not work properly because PersistentManager, etc. does not exist.
I can understand this.

**Expected behaviour**
The EditorInitializer exists and the Scene should operate normally.

If I understand correctly,
EditorInitializer No matter what Scene plays EditorMode, it can be tested and developed.

It does not seem to occur in other Scene (Location), so it seems to be a low-importance problem.
But I haven't confirmed the fundamental cause of this problem yet.
Is there any issue or concept i need to know about this?

**Comment by mejozzz** [comment]
actions asset on eventsystem currently using default, try it using gameinput 

![inputactions](https://user-images.githubusercontent.com/48565499/114786690-c0399d80-9da8-11eb-9cd1-6f94c7e32782.gif)

**Comment by amel-unity** [comment]
Hi @seoyeon01 , thanks for opening the issue, it's true. We are currently re working on the editor cold start and we don't think we will fix it in the new implementation considering that it is a hack and we mostly expect to use it to test the different locations but let's keep it as a minor bug in case we have time later we can try fix it

**Comment by ciro-unity** [comment]
Fixed in the latest changes on `main`. I'll close it. Thanks @seoyeon01 for reporting it!
