### ISSUE TITLE
The "save.chop" file it's not found when running the game in a different scene

### ISSUE THREAD

**Issue by JoaoSant0s** [UnityTechnologies/open-project-1#399]
**Problem**:

When we run the game without a save file in the persistence folder, using a scene differently of the **Initialization**, the following error is raised:

![image](https://user-images.githubusercontent.com/6272821/112785522-8b002200-902a-11eb-97d3-4ce3797fa6cd.png)

As you can see, the file save.chop don't exist yet, but the FileManager tries to move then to another path.

**Solution**:

To fix that, we must check if the previous save file exists.

**Steps to reproduce**:

1. Remove all save files in the persistence folder (or change temporary the name)
2. Open and run the Beach scene
3. You will see the error

**Comment by amel-unity** [comment]
Hi @JoaoSant0s, thank you for opening the issue. We will soon review the 2 PRs open to fix it :)
