### ISSUE TITLE
Avoid using magic numbers

### ISSUE THREAD

**Issue by MileyHollenberg** [UnityTechnologies/open-project-1#40]
**Short description**
There seem to be some classes which use magic numbers, magic numbers are defined by simply being put into the code as a direct value instead of through a parameter. When using magic numbers it can be difficult to know what they actually mean and if you use the same number multiple times it will be difficult to refactor this if you want to change the value later on.

**Expected behavior**
All numbers and other values should be stored in either private or public variables and no magic numbers should be allowed in the codebase. Logical numbers like -1 for error states, 0 and 1 for simple resets and 2 for dividing a value in half are numbers that I would not consider magic numbers, -5 and 0.02 (that I currently found in the code) I would consider magic numbers.

**Current findings**
https://github.com/UnityTechnologies/open-project-1/blob/master/UOP1_Project/Assets/Scripts/Characters/Character.cs#L81
https://github.com/UnityTechnologies/open-project-1/blob/master/UOP1_Project/Assets/Scripts/Characters/Character.cs#L92

**Notes**
This should become part of the style guide

**Comment by andrewreal** [comment]
I'd like to tackle this please.

**Comment by andrewreal** [comment]
For https://github.com/UnityTechnologies/open-project-1/blob/master/UOP1_Project/Assets/Scripts/Characters/Character.cs#L92 I'm not totally clear on what that value represents?

It seems to be a rotationSensitivty but can you suggest a better, more descriptive variable name for this?

**Comment by MileyHollenberg** [comment]
> For https://github.com/UnityTechnologies/open-project-1/blob/master/UOP1_Project/Assets/Scripts/Characters/Character.cs#L92 I'm not totally clear on what that value represents?
> 
> It seems to be a rotationSensitivty but can you suggest a better, more descriptive variable name for this?

Since it's referring to a movement vector I'd say it's a movement threshold of some sorts. @Quickz any idea what this value represents?

**Comment by TheBossBaby** [comment]
Can I have the chance to tackle this issue?
 From the comments: https://github.com/UnityTechnologies/open-project-1/blob/master/UOP1_Project/Assets/Scripts/Characters/Character.cs#L81

This value seems `verticalMovementReset` 

And for  https://github.com/UnityTechnologies/open-project-1/blob/master/UOP1_Project/Assets/Scripts/Characters/Character.cs#L92

I agree with @MileyHollenberg .

**Comment by casefc3s** [comment]
> > For https://github.com/UnityTechnologies/open-project-1/blob/master/UOP1_Project/Assets/Scripts/Characters/Character.cs#L92 I'm not totally clear on what that value represents?
> > It seems to be a rotationSensitivty but can you suggest a better, more descriptive variable name for this?
> 
> Since it's referring to a movement vector I'd say it's a movement threshold of some sorts. @Quickz any idea what this value represents?

It's a movement threshold to prevent NaN results from trying to rotate in a non-direction (zero-length vector), and potentially to also prevent jitter from small input sensitivity (e.g. a centered joystick on a gamepad is rarely actually zero) but the latter is an assumption.

**Comment by andrewreal** [comment]
Thanks for clarifying.

I've submitted this as PR https://github.com/UnityTechnologies/open-project-1/pull/55
