### ISSUE TITLE
Dialog Choice not selectable

### ISSUE THREAD

**Issue by TH3UNKN0WN-1337** [UnityTechnologies/open-project-1#428]
**Short description**
When having a Questline Dialog with a Choice at the end you can switch between "Yes" and "No" with your keyboard, but you can't actually make a choice. Since the Dialog Advance input is disabled at this point you only can use the mouse, but no UI element is clickable. 

**Expected behaviour**
You can make a choice either with keyboard or with mouse.

**To Reproduce**
1. Open Scene 'TestGround'
2. Go to 'The bard hare'
3. Talk to 'The bard hare'
4. Advance until dialogue 'actorBardHare'
5. Advance to the end of the Dialog until prompted to make a Choice
6. You can't make a choice

**Notes**
- UI is not clickable in Inventory UI as well.

**Comment by soloschenko-grigoriy** [comment]
Thank you for finding this! Just to confirm/clarify: I, for instance, can _click_ on the option but I cannot confirm selected option with the keyboard to make a choice

**Comment by uChema** [comment]
Hello ! Thanks for the report ! 
We had some issues while switching from fully mouse controlled to Mouse/Keyboard/Controllers at the same time. 
Right now, it should be working on main. 
Please tell us if this still persists for you. 
Thanks ,
