### ISSUE TITLE
Inventory Errors when empty

### ISSUE THREAD

**Issue by TH3UNKN0WN-1337** [UnityTechnologies/open-project-1#430]
**Short description**
When you have no items inside the inventory there will be NullRefereneExceptions thrown. Also when switching the active Inventory Tab the same exception is thrown.

**Expected behaviour**
When the Inventory is empty no exception is thrown.

**To Reproduce**
1. Open Inventory (with 'TAB')
2. Switch Inventory Tab (with 'T' and 'Y'/'Z')

**Notes**
![InventoryError](https://user-images.githubusercontent.com/55201839/118526177-464a5a80-b740-11eb-9175-9fd0ef97ea91.PNG)

**Comment by TH3UNKN0WN-1337** [comment]
Since I have no own fork of this repo here is a working fix inside InventoryItemFiller.cs
```cs
public void SelectItem()
{
	_imgSelected.gameObject.SetActive(true);

	if (!_currentItemEvent || _currentItem == null)
	{
		return;
	}

	_currentItemEvent.RaiseEvent(_currentItem.Item);
}
```

**Comment by uChema** [comment]
Thanks for the report ! 
This issue was taken care of ! 
When refactoring, we renamed some scripts. This is now called : UIInventoryItem.cs 
This is the new function : 
```
	public void SelectItem()
	{
		if (ItemSelected != null && _currentItem != null && _currentItem.Item != null)
		{
			_imgSelected.gameObject.SetActive(true);
			ItemSelected.Invoke(_currentItem.Item);
		}
		else
		{
			_imgSelected.gameObject.SetActive(false);
		}
	}
```
That way if no item is in the inventory, we wont even have the "_imgSelected" active !
