### ISSUE TITLE
Dialogue stopped working

### ISSUE THREAD

**Issue by soloschenko-grigoriy** [UnityTechnologies/open-project-1#431]
**Short description**
Cannot start the dialogue

**Expected behaviour**
Should be able to start dialogue

**To Reproduce**
1. Open`Testing Ground` and move to the townsfolk 
2. Press `E` when the menu pops up
3. Observe that instead of starting dialogue error message appears in the console

<img width="2032" alt="Screen Shot 2021-05-18 at 8 01 53 PM" src="https://user-images.githubusercontent.com/5962670/118738410-fbe6dd80-b814-11eb-932e-d829df921dd4.png">

<img width="1540" alt="Screen Shot 2021-05-18 at 8 02 00 PM" src="https://user-images.githubusercontent.com/5962670/118738424-02755500-b815-11eb-8aa0-2d90f25f4fd5.png">

**Comment by grimstoner** [comment]
This is caused a bug in the GameStateSO. 

PR raised to fix: https://github.com/UnityTechnologies/open-project-1/pull/438

**Comment by soloschenko-grigoriy** [comment]
Thank you @grimstoner looks like both of us came to the same fix 😊

**Comment by grimstoner** [comment]
Ah... Just saw your PR for the same fix 3 days ago... Apologies.

It seems like there's a lot of interest to contribute, but the moderators can't keep up.

**Comment by soloschenko-grigoriy** [comment]
No need to apologies 😊 Im just genially glad we came up to the same solution, it means more chances its a good solution 😄 Like in one saying, two heads are better than one 😊

**Comment by amel-unity** [comment]
Thank you @soloschenko-grigoriy and @grimstoner for mentioning the issue and proposing a solution. I will merge it now :)
