### ISSUE TITLE
Inventory close button doesn't work

### ISSUE THREAD

**Issue by grimstoner** [UnityTechnologies/open-project-1#439]
**Short description**
When having the Inventory dialog open, clicking the red cross in the top right-hand corner with a mouse does not close the Inventory dialog. Pressing Esc on the keyboard does close the inventory though.

**Expected behaviour**
Clicking this button should close the Inventory Dialog.

**To Reproduce**

1. Open Inventory dialog with Tab
2. Try and click close button

**Notes**
None

Forum thread link: https://forum.unity.com/threads/inventory-close-button-doesnt-work.1115896/

**Comment by dr-mimic** [comment]
this is working running Windows 10 Pro Unity 2020.3.7f1

what OS are you running / how are you running game ?

**Comment by uChema** [comment]
This should be working now ! 
Thanks for the report.
