### ISSUE TITLE
DialogueDataSO clearing Dialogue Lines

### ISSUE THREAD

**Issue by lteran9** [UnityTechnologies/open-project-1#446]
**Short description**
The SetDialogueLines and CreateLine line methods of the DialogueDataSO.cs class are clearing the _dialogueLines property. Not sure if there is a reason for this but it will break the gameplay on the TestingGrounds scene; mainly the Default-Earl dialogue scriptable object. 

**Expected behaviour**
1. Default-Earl dialogue line(s) not be deleted / cleared
2. Be able to talk with townsfolk

**To Reproduce**
1. Open WIP/TestingGround Scene
2. Click play
3. Attempt to talk to any Townsfolk that have the **Default-Earl** scriptable object as Default Dialogue
   - Notice the Default-Earl scriptable object dialogue lines is empty
   - The console shows an error and the character controls are broken

**Notes**
Commit Hash of version checked on: 4d1d04b286e06924d302a3558b06d750c2b74a44

**Comment by uChema** [comment]
Hey! 
My mistake, when pushing I forgot to switch the name for the scriptable object to Default-Townsfolk2 (which is the new placeholder for the character previously named "Earl" ). 
The DialogueDataSO has a function that fills the lines from the Localized String Table depending on the name of the SO. It should be resolved if you change the name of the SO to Default-Townsfolk2. A fix was just pushed to main!
Thanks for the report.
