### ISSUE TITLE
Deleting transition from table causes errors

### ISSUE THREAD

**Issue by pointfivetee** [UnityTechnologies/open-project-1#450]
In the transition table editor, removing the last transition in a list causes a bunch of NullReference exceptions while the table inspector disappears out of focus.

**Expected behaviour**
The transition should simply disappear from the list without error messages or changing the focus of the table inspector.

**To Reproduce**
1. Open the transition table editor.
2. Pick a "from" state in the table and click on the "-" button near the last transition in the sub-list.
3. A bunch of error messages appear in the log and the transition table becomes unselected in the left-hand side of the editor popup.

**Notes**
Forum thread: https://forum.unity.com/threads/how-to-delete-a-transition-from-the-transition-table.1104163/

**Comment by amel-unity** [comment]
Thanks a lot @pointfivetee for opening the issue and proposing a solution! The PR fixes it, I will merge it now :)
