### ISSUE TITLE
DOTween errors when building Player content.

### ISSUE THREAD

**Issue by Eyap53** [UnityTechnologies/open-project-1#462]
**Short description**
When trying to build player content (in the Addressable window), it fails.
It seems like the DOTween addon has some missing references.
(Error messages are like so : `Assets\Addons\DOTween\Modules\DOTweenModuleUI.cs(42,57): error CS0012: The type 'Vector2' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.`)

**Expected behavior**
Trying to build player content (in the Addressable window) works. It is a necessary step to build the game.

**To Reproduce**
1. Go to the Addressable window.
2. Then select Build > Build Player Content.

**Notes**
- Building the player content is a necessary step to build the game, so I believe it is a critical bug.
- The exact error message is : "Failed to compile player scripts"

**Comment by ciro-unity** [comment]
Just to add to this, I would be very surprised if DOTween was the issue because I've built versions of the game with it inside, and it's a very proven asset. Not sure why you see it pop up like that, probably a chain of previous errors leads to that?

**Comment by Eyap53** [comment]
Well, I was just as surprised !
I just tried to build the player content in Addressable Groups (not the actual build), and yeah I still got a lot of errors (around 500), and most of them seem to come from DOTween. It may be a chain of errors, but the inspector only shows that :

![image](https://user-images.githubusercontent.com/24421318/126351861-d603f4e7-0a66-4b83-ae02-280a2176c2f3.png)

I'm using the 2020.3.12f1, and I'm up-to-date with the latest commit from main (3217f0e7 from uChema), without any changes.

**Comment by ciro-unity** [comment]
So strange... did you try to "clean" the build before building, using the option in the Addressable Groups window?
I just did a content build and Unity peacefully built it in 6 minutes or so.

![image](https://user-images.githubusercontent.com/20049224/127153967-486d3326-8298-416b-897a-b6046d700863.png)

I'm not sure what could be causing that behaviour 🤔

**Comment by ciro-unity** [comment]
Closing since the issue doesn't seem to happen. (verified multiple times)

**Comment by ub3132003** [comment]
just install lv2cpp in unityHub. it's working in my project.
