### ISSUE TITLE
Loading the currently loaded scene gives error.

### ISSUE THREAD

**Issue by HarshNarayanJha** [UnityTechnologies/open-project-1#486]
Hey there. Whenever we try to load a scene, it gets loaded from the AssetBundle and the the scene is loaded. But if we try to load it again while it is loaded, Addressables gives error that the **Asset** is already loaded. And that is expected.

**Expected behaviour**
Expected behaviour is the scene assets should be properly unloaded, then again loaded. I tried this, but was unsuccessful. So what I just did if currently loaded is equal to the requested scene, just return.

**To Reproduce**
I exactly don't know how to reproduce it, but maybe user **stroibot** on forums may know this. He reported the issue to me.
But I tested it in the Debugging System I made, and that was reproduced.

**Notes**
Forum Thread: https://forum.unity.com/threads/reloading-scene-using-addressables.1149521/#post-7377545

Thanks.

**Comment by ciro-unity** [comment]
Sorry but this is not really an issue - unless I misunderstood? I'll be closing Issue and PR.
