### ISSUE TITLE
NullReferenceException on UniversalRenderPipelineAsset

### ISSUE THREAD

**Issue by obregons** [UnityTechnologies/open-project-1#52]
**Short description**
When opening the project in Unity, the following error messages show in the Editor Console:

> NullReferenceException: Object reference not set to an instance of an object
UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset.get_terrainDetailGrassBillboardShader () (at Library/PackageCache/com.unity.render-pipelines.universal@7.3.1/Runtime/Data/UniversalRenderPipelineAsset.cs:802)

> NullReferenceException: Object reference not set to an instance of an object
UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset.get_terrainDetailLitShader () (at Library/PackageCache/com.unity.render-pipelines.universal@7.3.1/Runtime/Data/UniversalRenderPipelineAsset.cs:792)

> NullReferenceException: Object reference not set to an instance of an object
UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset.get_terrainDetailGrassShader () (at Library/PackageCache/com.unity.render-pipelines.universal@7.3.1/Runtime/Data/UniversalRenderPipelineAsset.cs:797)

**Expected behaviour**
No error messages should be shown when opening the project the first time

**To Reproduce**
1. Fork the project in GitHub
2. Clone the forked project into a Mac development machine
3. Add the project to the list of project in Unity Hub
4. Open the project in Unity
5. When all the components have finished loading, the error messages show in the Console tab

**Notes**
- Unity Hub version: 2.4.1
- Unity Version: 2019.4.11f1
- MacOS version: Catalina 10.15.6
- This errors are only showing when the project is opened for the first time
- Project commit where this bug is observed: "21bd0e2 Merge pull request #37 from Acimaz/TMPro-Import"
- Attaching screenshot showing error messages

<img width="1399" alt="Screen Shot 2020-10-03 at 12 32 03 PM" src="https://user-images.githubusercontent.com/44950066/95000300-80316c80-0574-11eb-9641-082cd33beeb5.png">

**Comment by GintasS** [comment]
Couldn't reproduce, but maybe that's because I upgraded the project to the 2019.4.11f version. This was required to run the project.

**Comment by ciro-unity** [comment]
While I recognise the error message, it's something that goes away with a Clear in the console and has no impact on development, so it's very minor.
