### ISSUE TITLE
Player climb up by clipping through building

### ISSUE THREAD

**Issue by alifsamudra74** [UnityTechnologies/open-project-1#58]
**Short description**
Player can climb up buildings by clipping through the edge of a building while jumping

**Expected behaviour**
Reach maximum jump height then fall down

**To Reproduce**
1. Play the scene
2. Go to the side of a bulding
3. Click space (jump)
4. Immediately move toward the building
5. Player got clipped through the building then move upwards

**Notes**
![Unity_llA9hQciUJ (2)](https://user-images.githubusercontent.com/58199331/95019415-689ad680-068f-11eb-9b9b-f46914a29b7a.png)

**Comment by ciro-unity** [comment]
Do you think this might be related to #48? Seems very similar.

**Comment by Quickz** [comment]
Seems like same as #48 but with a more straightforward explanation.

**Comment by MEGATANK58** [comment]
This is same as #48 The player is able to do that because of the Character collider near the legs which is happening because players can climb steep surfaces #8

**Comment by alifsamudra74** [comment]
Oh, sorry if it already issued. Maybe my description is a little bit more spesific to climbing buildings

**Comment by MEGATANK58** [comment]
> Oh, sorry if it already issued. Maybe my description is a little bit more spesific to climbing buildings

Yes, but cause of the issue is same
