### ISSUE TITLE
Movement is very snappy when changing directions while using Keyboard controls

### ISSUE THREAD

**Issue by ciro-unity** [UnityTechnologies/open-project-1#7]
**Short description**
When using the keyboard, the movement of the character is very snappy.

**Expected behaviour**
The character smoothly rotates to face the direction of movement.

**To Reproduce**
1. Open the gameplay scene, press Play.
2. Move the character with arrow keys or WASD (not joypad). Press up, then right, without releasing the previous key.
3. Notice the character changes direction abruptly

**Notes**
- If we fix this, we need to make sure it plays nice with joystick movement too.

**Comment by DapperDino** [comment]
I would like to solve this bug!

**Comment by DapperDino** [comment]
I would like to fix this bug!

**Comment by ciro-unity** [comment]
Hey @DapperDino, for sure! I'll assign it to you on the roadmap. Thanks!

Here's the card, btw: https://unity-open-projects.codecks.io/decks/13/card/16e-movement-is-very-snappy-if-using-keyboard
