### ISSUE TITLE
Got a bunch of errors while opening the project

### ISSUE THREAD

**Issue by HarshNarayanJha** [UnityTechnologies/open-project-1#78]
I downloaded the project from here(github) and opened it in unity editor, I then got many resolving packages error, so i connected to internet and then reimported. It then downloaded all the packages, but when editor open and i hit the play button, i noticed there were still some errors

... is inaccessible due to itsbprotection level  

failed to load ... because it was serialized with a higher version of unity

And many more (999+)
I am not able to even run the game, please help
(Sorry if I broke any guidelines)

**Comment by MEGATANK58** [comment]
This is not a global error (yet) and it doesn't happens to everyone so probably not a issue as well,However can you show the screenshots of the errors.

**Comment by AyoubGharbi** [comment]
Hey @HarshNarayanJha,
The current Unity's version of the project is 2019.4.11f1, make sure you are opening the project with a 2019.4.x version or above.

**Comment by MEGATANK58** [comment]
> I downloaded the project from here(github) and opened it in unity editor, I then got many resolving packages error, so i connected to internet and then reimported. It then downloaded all the packages, but when editor open and i hit the play button, i noticed there were still some errors
> 
> ... is inaccessible due to itsbprotection level
> 
> failed to load ... because it was serialized with a higher version of unity
> 
> And many more (999+)
> I am not able to even run the game, please help
> (Sorry if I broke any guidelines)

It's happening because you have a lower version of unity you don't need to worry about this but I'll suggest to upgrade to Unity 2019.4.11f (as @AyoubGharbi suggested)

**Comment by ciro-unity** [comment]
Yes, like the others say, we're currently on 2019.4.11 so please use that version or newer, and you should get no errors.
Closing.
