### ISSUE TITLE
Player can climb steep surfaces

### ISSUE THREAD

**Issue by ciro-unity** [UnityTechnologies/open-project-1#8]
**Short description**
The player can climb very steep surfaces if it spams the jump button.

**Expected behaviour**
One would expect the player to slide down, and to be prevented from jumping if not on a stable surface.

**To Reproduce**
1. Open gameplay scene, press Play.
2. Move up the mountain made with Terrain.
3. Keep moving, the player will stop on a steep slope.
4. Press the jump button. Now you can climb up by jumping repeatedly.

**Comment by scascar** [comment]
I'd like to work on this issue.

**Comment by ciro-unity** [comment]
Oh no, an overlap! Oscar, maybe you can jump in the PR #12 and check if the solution works / the code is good?

**Comment by dhumildholiya-code** [comment]
Hello, I'd Like to work on this issue. Let me know if it's not assigned.

**Comment by richard-fine** [comment]
Related to this: If the player is walking up a steep-but-not-too-steep surface, should they move more slowly? I think that if you walk up a slope which is gradually increasing in steepness, it'd be strange to move at full speed and then suddenly be stopped. 

Making the player walk more slowly depending on how much the ground is sloping upwards will better communicate to the player that they're approaching a limit on how steep the ground can be.

**Comment by MEGATANK58** [comment]
@ciro-unity I actually tested the game today again and the bug is still there
