### ISSUE TITLE
Add Hacktoberfest tag

### ISSUE THREAD

**Issue by chessboards** [UnityTechnologies/open-project-1#81]
**Short description**
Not a bug, but more so a suggestion/enhancement to add the tag `hacktoberfest` to the repository.

**Expected behavior**
Doing so would bring forth more contributors, and would participate in an open source oriented event that is intended to bring in more developers, as well as to plant trees for every person eligible in the event if they choose.

**To Reproduce**
Visit https://hacktoberfest.digitalocean.com/  for more information if you are a maintainer.

**Notes**
n/a

**Comment by MEGATANK58** [comment]
Not really a issue, i would suggest you to open a thread at Unity forum with Feature request tag for the suggestion

**Comment by ciro-unity** [comment]
Sorry, but we're not going to take part in Hacktober. While the fest in itself is a great idea, it seems to attract a lot of spammy PRs for the sole goal of winning the t-shirt.

Read this too: https://hacktoberfest.digitalocean.com/hacktoberfest-update
