### ISSUE TITLE
rename default branch from `master` to `main`

### ISSUE THREAD

**Issue by AlexChesser** [UnityTechnologies/open-project-1#84]
While the change is expected to be coming to github overall, there is a move to rename default branches to `main` 

https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

The scale and scope of the change is small enough that it only takes a few seconds to do

more background https://jarv.is/notes/github-rename-master/

**Comment by ciro-unity** [comment]
We can do. The only investment is having to keep master for all the existing open PRs, and manually merge them to `master` first and then to `main`. But it shouldn't be a big deal of work.
For new PRs - once we make `main` the default branch, it should just be automatic. Right?

https://github.com/github/renaming

**Comment by AlexChesser** [comment]
I recently went through this exercise on our production environments at work. Around 50 repos didn't take much time at all. I tend to think the rip-off-the-band-aid approch is needed here, since at no point are there going to be FEWER pull requests.

Pull requests are blissfully easy to edit and it can 100% be done within the github website interface I can't imagine the change taking more than 15 minutes. 

1. create a new branch by typing `main` in the website dropdown and hitting enter

> ![image](https://user-images.githubusercontent.com/355561/96002728-737c0680-0e07-11eb-94b9-f5241dc1497d.png)

2. in the list of branches choose the `change-default-branch` button beside `master`

> ![image](https://user-images.githubusercontent.com/355561/96002944-b76f0b80-0e07-11eb-8487-b58c41e525e0.png)

3. in each of the open PRs select the EDIT button

> ![image](https://user-images.githubusercontent.com/355561/96002288-f2247400-0e06-11eb-9985-7b341bf9c74d.png)

4. in the subject-line-dropdown alter the BASE to `main` and save

> ![image](https://user-images.githubusercontent.com/355561/96003196-f9984d00-0e07-11eb-9aa0-5db36bc7f817.png)

5. delete master branch

> ![image](https://user-images.githubusercontent.com/355561/96003311-1a60a280-0e08-11eb-994f-34699f608de7.png)

@ciro-unity

**Comment by AlexChesser** [comment]
> For new PRs - once we make main the default branch, it should just be automatic. Right?

yes - all new PRs will come in to `main` by default once you complete steps 1 and 2 above!

**Comment by ciro-unity** [comment]
> 1. **in the subject-line-dropdown alter the BASE to `main` and save**

Ah that's great, I didn't know I could edit the PRs' target branch like that. I'll get on this then.

**Comment by ManuelRauber** [comment]
> > 1. **in the subject-line-dropdown alter the BASE to `main` and save**
> 
> Ah that's great, I didn't know I could edit the PRs' target branch like that. I'll get on this then.

You can also, if you need to, target another PR for example and GitHub will retarget dependent PRs if the base PR gets merged. Quite nice, if you have a bigger PR for refactoring split into several smaller PRs.

**Comment by ciro-unity** [comment]
> several smaller PRs

I've never seen this concept happen on this repo yet 🤣
