### ISSUE TITLE
> For new PRs - once we make main the default branch, it should just be automatic. Right?

### ISSUE THREAD

**Issue by 0479010347** [UnityTechnologies/open-project-1#92]
> For new PRs - once we make main the default branch, it should just be automatic. Right?

yes - all new PRs (~~will~~) should come in to `main` by default once you complete steps 1 and 2 above!

__Originally posted by @AlexChesser in https://github.com/UnityTechnologies/open-project-1/issues/84#issuecomment-708445107__

**Comment by MEGATANK58** [comment]
Um whats your issue, please dont open unnecessary issues without a valid reason

**Comment by ciro-unity** [comment]
@0479010347 this is not a forum, please don't use issues as conversations, thanks.
Here's a guide on Issues: https://guides.github.com/features/issues/
