### ISSUE TITLE
Upgrade to latest 2019.4 LTS version

### ISSUE THREAD

**Issue by Remwrath** [UnityTechnologies/open-project-1#96]
Latests LTS is now 2019.4.12f1 ;)

**Comment by MEGATANK58** [comment]
I don't think we need a upgrade yet,there is no specific reason to do so and most of the people can't just keep updating and redownloading Unity every week or so just to be latest.

**Comment by SoundGuy** [comment]
@MEGATANK58  you don't really need to update your installation between minor updates. I'm on 2019.4.12f but i don't commit the  version file. 

it would be nice if it was upgraded so i won't have that version file changed in my working copy - becuase i need to stash or discard it every time i check out another branch (along with a few other annyoying files i wish there was a way to just tell git to ignore because i will never commi them myself)

**Comment by SoundGuy** [comment]
also the packages in my unity installation are newer and then change the manifest file every time i open the project

{
  "dependencies": {
    "com.unity.addressables": "1.8.5",
    "com.unity.cinemachine": "2.6.0",
    "com.unity.ide.rider": "1.1.4",
    "com.unity.ide.vscode": "1.2.1",
    "com.unity.inputsystem": "1.0.0",
    "com.unity.polybrush": "1.0.2",
    "com.unity.probuilder": "4.2.3",
    "com.unity.progrids": "3.0.3-preview.6",
    "com.unity.render-pipelines.universal": "7.3.1",
    "com.unity.settings-manager": "1.0.3",
    "com.unity.textmeshpro": "2.0.1",
    "com.unity.timeline": "1.2.15",
    "com.unity.ugui": "1.0.0",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}

**Comment by Eyap53** [comment]
2019.4.13f1 is live.

**Comment by Hemanth759** [comment]
> @MEGATANK58 you don't really need to update your installation between minor updates. I'm on 2019.4.12f but i don't commit the version file.
> 
> it would be nice if it was upgraded so i won't have that version file changed in my working copy - becuase i need to stash or discard it every time i check out another branch (along with a few other annyoying files i wish there was a way to just tell git to ignore because i will never commi them myself)

you can tell git to ignore some file adding that files to `.gitignore` file
Just a simple tutorial I found on youtube for gitignore file https://youtu.be/4a2ZVSzMMq8

**Comment by SoundGuy** [comment]
.gitignore doesn’t work on files already added to the repository .

**Comment by Hemanth759** [comment]
> .gitignore doesn’t work on files already added to the repository . 

True, totally forgot about that 😅

**Comment by MEGATANK58** [comment]
> @MEGATANK58  you don't really need to update your installation between minor updates. I'm on 2019.4.12f but i don't commit the  version file. 
> 
> it would be nice if it was upgraded so i won't have that version file changed in my working copy - becuase i need to stash or discard it every time i check out another branch (along with a few other annyoying files i wish there was a way to just tell git to ignore because i will never commi them myself)

Oh yes, right!

**Comment by ciro-unity** [comment]
Closing because it's not really an issue, we will update every now and then as needed.
